# Generated by Django 6.0.2 on 2026-02-12 12:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='title',
            field=models.CharField(default=datetime.datetime(2026, 2, 12, 12, 6, 22, 358598, tzinfo=datetime.timezone.utc), max_length=200),
        ),
    ]
